spring.application.name=SpringBootLogin
spring.datasource.url=jdbc:postgresql://localhost:5433/SpringBootLogin
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver